---
title: "Week_6_NFL"
author: ""
date: "2023-03-23"
output: 
  html_document:
    toc: true
---
```{r, echo=FALSE}
library(readr)
library(dplyr)
library(rsample)
library(ggplot2)
library(tidyr)
library(knitr)
library(kableExtra)
library(stargazer)
```



# Load data from github:
```{r, message=FALSE, warning=FALSE, echo=FALSE}
set.seed(1234)
attendance <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv")
standings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv")
```


```{r}
head(attendance) %>% 
  kable() %>% 
  kableExtra::kable_styling(bootstrap_options = "striped",
                            full_width = F)
```
```{r}
head(standings) %>% 
  kable() %>% 
  kableExtra::kable_styling(bootstrap_options = "striped",
                            full_width = F)
```

## Joining the datasets

```{r}
attendance_joined <- attendance %>%
  left_join(standings,
    by = c("year", "team_name", "team")
  )
```



```{r}
attendance_df <- attendance_joined %>%
  filter(!is.na(weekly_attendance)) %>%
  select(
    weekly_attendance, team_name, year, week,
    margin_of_victory, strength_of_schedule, playoffs, points_differential
  )
```
# Converting character columns to factor

```{r}
attendance_df <- attendance_df %>% 
  mutate(across(where(is.character),as.factor))
```

# Choosing reference category

```{r}
attendance_df <- attendance_df %>% 
  mutate(team_name = relevel(team_name, ref = "Jets"))
```


# Estimating linear regression

```{r}
model_1 <- lm(weekly_attendance ~ margin_of_victory + week + team_name + year + 
                strength_of_schedule + playoffs + points_differential , data = attendance_df)

summary(model_1)
```


