- readr
- dplyr
- tidyr
- stringr
- tibble
- broom
- ggplot2
- patchwork
- stargazer
- manipulate
- rmarkdown
- knitr
- kableExtra
- tidyr
- purrr
- gganimate
- flexdashboard
- gifski
- svglite
- tidymodels
- rsample
- forcats
- corrplot
