---
title: "heteroskedaticity vs. BLUE"
author: "Dominik Kavřík"
date: "10/21/2021"
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---



```{r}
library(tidyverse)
theme_set(theme_light())
```

# Simulate data with heteroskedastic errors
```{r}
set.seed(123)
N=100000
IQ=rnorm(N,100,5)
expert=as.numeric(runif(N, min=0, max=30))
educ = as.numeric(runif(N, min=9, max=20))  
sigma=2*(exp(educ))^0.5             # conditional variance depends on regressor 
e4= rnorm(N, 0, sigma)  
wage = -50 +10*IQ+ 50*educ+3*expert + e4       
population = data.frame(IQ,expert, educ, wage)
```


```{r}
A <- list(tibble(NA))
R <-  1000

for (i in 1:R){
  
  A[[i]] <- sample_n(population, 800)
}
samples <- tibble(sample = A)

samples %>%
  mutate(model = map(sample, .f= ~lm(wage ~ educ + expert + IQ, data = .)),
         coeffs = map(model, .f = broom::tidy)) %>%
  unnest(coeffs) %>% 
  mutate(true_val = case_when(term=="(Intercept)" ~ -50,
                              term == "IQ" ~10,
                              term == "educ" ~ 50,
                              term == "expert" ~ 3)) -> estimates
```


```{r}
data <- A[[10]]

# write.csv(data, "H_data.csv", row.names = FALSE, fileEncoding = "UTF-8")
```


```{r}
estimates %>%
  ggplot(aes(x=estimate))+ 
  geom_vline(aes(xintercept =true_val))+
  geom_histogram(color="dodgerblue2", fill="dodgerblue2", alpha=0.5)+
  facet_wrap(~term,scales="free")
```


# Weighted least squares (WLS)
```{r}
samples %>% 
  mutate(model_wls = map(sample, .f = ~lm(wage ~ educ + expert + IQ, weights =(1/exp(educ)^0.5), data=.)),
         coeffs_wls = map(model_wls, .f=broom::tidy)) %>% 
  unnest(coeffs_wls) %>% 
  mutate(true_val = case_when(term=="(Intercept)" ~ -50,
                              term == "IQ" ~10,
                              term == "educ" ~ 50,
                              term == "expert" ~ 3)) -> estimates_wls
estimates %>%
  ggplot(aes(x=estimate))+ 
  geom_vline(aes(xintercept =true_val))+
  geom_histogram(aes(x=estimate),data=estimates_wls,color="red2", fill="red2", alpha=0.5)+
  geom_histogram(color="dodgerblue2", fill="dodgerblue2", alpha=0.5)+
  facet_wrap(~term,scales="free")
```


# Probability density
```{r}
estimates %>%
  ggplot(aes(x=estimate))+ 
  geom_vline(aes(xintercept =true_val))+
  geom_density(aes(x=estimate),data=estimates_wls,color="red2", fill="red2", alpha=0.5)+
  geom_density(color="dodgerblue2", fill="dodgerblue2", alpha=0.5)+
  facet_wrap(~term,scales="free")
```


```{r}
mod1 <- lm(wage ~ IQ + educ + expert, data = data)
summary(mod1)

library(sandwich)
library(lmtest)
coeftest(mod1, vcov = vcovHC, type = "HC2")
```




```{r, include=FALSE}
knitr::knit_exit()
```
